# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79840865a58a183d4581ba6400d678324c6ae4e33d79e3abd03b3afa8421ca4e255796766b08f7a3cee8a6d7af37cd82a5ee8d0acace90840d80d372469d2630

test:
  secret_key_base: b1ce1a402309dabd488b8abb028d52bdfa8db9594998ff3bf2b290f4fa46002033480bba63306b8b804b7bd7dec6b836b34adef715395c8b18814febbb67fa38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
